### PR TITLE
Support for Spring

### PR DESCRIPTION
**Pull request by sdorra**
This PR will add a Spring based CommandBus in addition to the existing CDI based one.

### CODE REVIEW

**Comment by schnatterer** [comment]
We just discussed that using the command-bus in Spring requires a CDI dependency.

That's not ideal.

A solution could be a more modular command-bus (in terms of maven modules), e.g. like so:

* `command-bus-api`, 
* `command-bus-spring` and
* `command-bus-cdi`

Users can then either use the  `command-bus-spring` or `command-bus-cdi` dependencies.

This would be a major change, as user would need to include a different dependency as of right now.
A good time for version 1.0.0 😁

**Comment by triomarvin** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [CDIExtension.java#L71](https://github.com/triologygmbh/command-bus/blob/4cf3b28980432ea77d1d0c28f7afa2c983fe6181/command-bus-cdi/src/main/java/de/triology/cb/cdi/CDIExtension.java#L71): Remove useless curly braces around statement [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1602)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by triomarvin** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [CDIExtension.java#L71](https://github.com/triologygmbh/command-bus/blob/5fe66e6251278a233f30c4abd585b5a88ac43331/command-bus-cdi/src/main/java/de/triology/cb/cdi/CDIExtension.java#L71): Remove useless curly braces around statement [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1602)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by triomarvin** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [CDIExtension.java#L71](https://github.com/triologygmbh/command-bus/blob/5e5dd86ec9d0519b95c50e9f3d63549298e5e413/command-bus-cdi/src/main/java/de/triology/cb/cdi/CDIExtension.java#L71): Remove useless curly braces around statement [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1602)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by triomarvin** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [CDIExtension.java#L71](https://github.com/triologygmbh/command-bus/blob/0b2d32d06d73fb17aa4c046d7be175479b0ccae7/command-bus-cdi/src/main/java/de/triology/cb/cdi/CDIExtension.java#L71): Remove useless curly braces around statement [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1602)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
